            - name: Renovate Bot GitHub Action
  # You may pin to the exact commit or the version.
  # uses: renovatebot/github-action@aa150c86873c3e1326734d9c1390064fbc646148
  uses: renovatebot/github-action@v36.0.0
  with:
    # Configuration file to configure Renovate. Either use this input or the
'RENOVATE_CONFIG_FILE' environment variable.

    configurationFile: # optional
    # GitHub personal access token that Renovate should use. This should be
configured using a Secret. Either use this input or the 'RENOVATE_TOKEN'
environment variable.

    token: # optional
    # Use a lightweight renovate container without any third-party binaries.
Defaults to true if not set.

    useSlim: # optional
    # Override the environment variables which will be passsed into the renovate container.
Defaults to `^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS)$`

    env-regex: # optional
    # Renovate version to use. Defaults to latest.

    renovate-version: # optional
          
